// This file was generated by sql-embedder. Do not edit manually.

/**
 * namespaces table: stores tenant namespaces
 */
export const namespaces =
  "CREATE TABLE IF NOT EXISTS namespaces (\n  id TEXT PRIMARY KEY,\n  label TEXT NOT NULL,\n  created_at INTEGER NOT NULL,\n  updated_at INTEGER NOT NULL\n);";

/**
 * selectNamespaceById retrieves a namespace by its ID.
 */
export const selectNamespaceById =
  "SELECT id, label, created_at, updated_at FROM namespaces WHERE id = ?;";

/**
 * selectAllNamespaces retrieves all namespaces with cursor-based pagination.
 * cursor is encoded as created_at:id
 */
export const selectAllNamespaces =
  "SELECT id, label, created_at, updated_at FROM namespaces\nWHERE (? IS NULL OR (created_at < ? OR (created_at = ? AND id < ?)))\nORDER BY created_at DESC, id DESC\nLIMIT ?;";

/**
 * insertNamespace creates a new namespace (idempotent).
 */
export const insertNamespace =
  "INSERT OR IGNORE INTO namespaces (id, label, created_at, updated_at) VALUES (?, ?, ?, ?);";

/**
 * updateNamespace updates a namespace's label.
 */
export const updateNamespace =
  "UPDATE namespaces SET label = ?, updated_at = ? WHERE id = ?;";

/**
 * deleteNamespace removes a namespace by its ID.
 */
export const deleteNamespace = "DELETE FROM namespaces WHERE id = ?;";

/**
 * api_keys table: stores API keys (key_hash = SHA256 of the API key)
 */
export const api_keys =
  "CREATE TABLE IF NOT EXISTS api_keys (\n  key_hash TEXT PRIMARY KEY,\n  namespace TEXT,\n  created_at INTEGER NOT NULL,\n  FOREIGN KEY (namespace) REFERENCES namespaces(id) ON DELETE CASCADE\n);";

/**
 * selectNamespaceByApiKey retrieves a namespace by hashed API key.
 */
export const selectNamespaceByApiKey =
  "SELECT namespace FROM api_keys WHERE key_hash = ?;";

/**
 * insertApiKey creates a new API key (idempotent).
 */
export const insertApiKey =
  "INSERT OR IGNORE INTO api_keys (key_hash, namespace, created_at) VALUES (?, ?, ?);";

/**
 * deleteApiKey removes an API key.
 */
export const deleteApiKey = "DELETE FROM api_keys WHERE key_hash = ?;";

/**
 * worlds table: stores world metadata per namespace
 */
export const worlds =
  "CREATE TABLE IF NOT EXISTS worlds (\n  rowid INTEGER PRIMARY KEY,\n  namespace TEXT,\n  id TEXT,\n  label TEXT NOT NULL,\n  description TEXT,\n  db_hostname TEXT,\n  db_token TEXT,\n  created_at INTEGER NOT NULL,\n  updated_at INTEGER NOT NULL,\n  deleted_at INTEGER,\n  UNIQUE (namespace, id),\n  FOREIGN KEY (namespace) REFERENCES namespaces(id) ON DELETE CASCADE\n);";

/**
 * selectWorldById retrieves a world by id and namespace.
 */
export const selectWorldById =
  "SELECT namespace, id, label, description, db_hostname, db_token, created_at, updated_at, deleted_at\nFROM worlds\nWHERE id IS ? AND namespace IS ? AND deleted_at IS NULL;";

/**
 * selectWorldByIdInternal retrieves a world by id without namespace scoping.
 */
export const selectWorldByIdInternal =
  "SELECT namespace, id, label, description, db_hostname, db_token, created_at, updated_at, deleted_at\nFROM worlds\nWHERE id IS ? AND deleted_at IS NULL;";

/**
 * selectAllWorlds retrieves worlds for a specific namespace with cursor-based pagination.
 * cursor is encoded as created_at:id
 */
export const selectAllWorlds =
  "SELECT namespace, id, label, description, db_hostname, db_token, created_at, updated_at, deleted_at\nFROM worlds\nWHERE namespace IS ? AND deleted_at IS NULL\nAND (? IS NULL OR (created_at < ? OR (created_at = ? AND id < ?)))\nORDER BY created_at DESC, id DESC\nLIMIT ?;";

/**
 * insertWorld creates a new world.
 */
export const insertWorld =
  "INSERT INTO worlds (namespace, id, label, description, db_hostname, db_token, created_at, updated_at, deleted_at)\nVALUES (?, ?, ?, ?, ?, ?, ?, ?, ?);";

/**
 * updateWorld updates world fields.
 */
export const updateWorld =
  "UPDATE worlds\nSET label = ?, description = ?, db_hostname = ?, db_token = ?, updated_at = ?, deleted_at = ?\nWHERE id IS ? AND namespace IS ?;";

/**
 * deleteWorld removes a world by id and namespace.
 */
export const deleteWorld =
  "DELETE FROM worlds WHERE id IS ? AND namespace IS ?;";
