// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * A text chunk with an optional embedding vector.
 */
export type Chunk = {
    id: ChunkId;
    fact_id: string;
    subject: string;
    predicate: string;
    text: string;
    /**
     * Base64-encoded embedding vector (Uint8Array).
     */
    vector?: string;
};

/**
 * A branded identifier for a Chunk resource.
 */
export type ChunkId = string;

/**
 * Supported RDF serialization content types.
 */
export type ContentType = 'text/turtle' | 'application/n-quads' | 'application/n-triples' | 'text/n3';

export type CreateWorldRequest = {
    parent?: string;
    id?: string;
    displayName?: string;
    description?: string;
};

export type DeleteWorldRequest = {
    source: Source;
};

export type ErrorResponseData = {
    error: {
        message: string;
    };
};

export type ExportWorldRequest = {
    source: Source;
    contentType?: ContentType;
};

/**
 * A single triple/quad in a world.
 */
export type Fact = {
    id?: FactId;
    subject: string;
    predicate: string;
    object: string;
    type: string;
    lang?: string;
    datatype?: string;
    world_id?: string;
    created_at?: number;
    deleted_at?: number | null;
};

/**
 * A branded identifier for a Fact resource.
 */
export type FactId = string;

export type GetWorldRequest = {
    source: Source;
};

export type ImportWorldRequest = {
    source: Source;
    /**
     * RDF data to import (can be base64-encoded).
     */
    data: string;
    contentType?: ContentType;
};

export type ListWorldsRequest = {
    parent?: string;
    pageSize?: number;
    pageToken?: string;
};

export type ListWorldsResponse = {
    worlds: Array<World>;
    nextPageToken?: string;
};

export type Log = {
    level: string;
    message: string;
    timestamp: number;
    metadata?: {
        [key: string]: unknown;
    };
};

export type SearchResult = {
    subject: string;
    predicate: string;
    object: string;
    vecRank?: number;
    ftsRank?: number;
    score: number;
    world: World;
};

export type SearchWorldsRequest = {
    sources?: Array<Source>;
    parent?: string;
    query: string;
    pageSize?: number;
    pageToken?: string;
    subjects?: Array<string>;
    predicates?: Array<string>;
    types?: Array<string>;
};

export type Source = string | {
    name?: string;
    id?: string;
    namespace?: string;
    mode?: TransactionMode;
};

export type SparqlAskResults = {
    head: {
        link?: Array<string>;
    };
    boolean: boolean;
};

export type SparqlBinding = {
    [key: string]: SparqlValue;
};

export type SparqlQuad = {
    subject: {
        type: 'uri' | 'bnode';
        value: string;
    };
    predicate: {
        type: 'uri';
        value: string;
    };
    object: SparqlValue;
    graph: {
        type: 'default' | 'uri';
        value: string;
    };
};

export type SparqlQuadsResults = {
    head: {
        link?: Array<string>;
    };
    results: {
        quads: Array<SparqlQuad>;
    };
};

export type SparqlQueryRequest = {
    sources?: Array<Source>;
    parent?: string;
    query: string;
    defaultGraphUris?: Array<string>;
    namedGraphUris?: Array<string>;
};

export type SparqlQueryResponse = SparqlSelectResults | SparqlAskResults | SparqlQuadsResults | null;

export type SparqlSelectResults = {
    head: {
        vars: Array<string>;
        link?: Array<string>;
    };
    results: {
        bindings: Array<SparqlBinding>;
    };
};

/**
 * A value in a SPARQL result.
 */
export type SparqlValue = {
    type: 'uri';
    value: string;
} | {
    type: 'bnode';
    value: string;
} | {
    type: 'literal';
    value: string;
    'xml:lang'?: string;
    datatype?: string;
} | {
    type: 'triple';
    value: {
        subject: SparqlValue;
        predicate: SparqlValue;
        object: SparqlValue;
    };
};

/**
 * Transaction behavior for source access.
 */
export type TransactionMode = 'write' | 'read' | 'deferred';

export type UpdateWorldRequest = {
    source: Source;
    displayName?: string;
    description?: string;
};

/**
 * Metadata for a single world.
 */
export type World = {
    /**
     * The canonical resource name.
     */
    readonly name?: string;
    id?: WorldId;
    namespace?: string;
    displayName: string;
    description?: string;
    createTime?: number;
    updateTime?: number;
    deleteTime?: number | null;
};

/**
 * A branded identifier for a World resource.
 */
export type WorldId = string;

export type ListWorldsResponseWritable = {
    worlds: Array<WorldWritable>;
    nextPageToken?: string;
};

export type SearchResultWritable = {
    subject: string;
    predicate: string;
    object: string;
    vecRank?: number;
    ftsRank?: number;
    score: number;
    world: WorldWritable;
};

/**
 * Metadata for a single world.
 */
export type WorldWritable = {
    id?: WorldId;
    namespace?: string;
    displayName: string;
    description?: string;
    createTime?: number;
    updateTime?: number;
    deleteTime?: number | null;
};

export type WorldsRpcData = {
    body: GetWorldRequest | CreateWorldRequest | UpdateWorldRequest | DeleteWorldRequest | ListWorldsRequest | ImportWorldRequest | ExportWorldRequest | SearchWorldsRequest | SparqlQueryRequest;
    path?: never;
    query?: never;
    url: '/rpc/worlds';
};

export type WorldsRpcResponses = {
    /**
     * Success
     */
    200: World | ListWorldsResponse | SparqlQueryResponse | {
        results?: Array<SearchResult>;
        nextPageToken?: string;
    };
};

export type WorldsRpcResponse = WorldsRpcResponses[keyof WorldsRpcResponses];
