// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

/**
 * A branded identifier for a Chunk resource.
 */
export const zChunkId = z.string();

/**
 * A text chunk with an optional embedding vector.
 */
export const zChunk = z.object({
    id: zChunkId,
    fact_id: z.string(),
    subject: z.string(),
    predicate: z.string(),
    text: z.string(),
    vector: z.string().nullish()
});

/**
 * Supported RDF serialization content types.
 */
export const zContentType = z.enum([
    'text/turtle',
    'application/n-quads',
    'application/n-triples',
    'text/n3'
]);

export const zCreateWorldRequest = z.object({
    parent: z.string().optional(),
    id: z.string().optional(),
    displayName: z.string().optional(),
    description: z.string().optional()
});

export const zErrorResponseData = z.object({
    error: z.object({
        message: z.string()
    })
});

/**
 * A branded identifier for a Fact resource.
 */
export const zFactId = z.string();

/**
 * A single triple/quad in a world.
 */
export const zFact = z.object({
    id: zFactId.optional(),
    subject: z.string(),
    predicate: z.string(),
    object: z.string(),
    type: z.string(),
    lang: z.string().optional(),
    datatype: z.string().optional(),
    world_id: z.string().optional(),
    created_at: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    deleted_at: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).nullish()
});

export const zListWorldsRequest = z.object({
    parent: z.string().optional(),
    pageSize: z.int().optional(),
    pageToken: z.string().optional()
});

export const zLog = z.object({
    level: z.string(),
    message: z.string(),
    timestamp: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }),
    metadata: z.record(z.string(), z.unknown()).optional()
});

export const zSparqlAskResults = z.object({
    head: z.object({
        link: z.array(z.string()).nullish()
    }),
    boolean: z.boolean()
});

/**
 * A value in a SPARQL result.
 */
export const zSparqlValue = z.union([
    z.object({
        type: z.enum(['uri']),
        value: z.string()
    }),
    z.object({
        type: z.enum(['bnode']),
        value: z.string()
    }),
    z.object({
        type: z.enum(['literal']),
        value: z.string(),
        'xml:lang': z.string().optional(),
        datatype: z.string().optional()
    }),
    z.object({
        type: z.enum(['triple']),
        value: z.object({
            subject: z.lazy((): any => zSparqlValue),
            predicate: z.lazy((): any => zSparqlValue),
            object: z.lazy((): any => zSparqlValue)
        })
    })
]);

export const zSparqlBinding = z.record(z.string(), zSparqlValue);

export const zSparqlQuad = z.object({
    subject: z.object({
        type: z.enum(['uri', 'bnode']),
        value: z.string()
    }),
    predicate: z.object({
        type: z.enum(['uri']),
        value: z.string()
    }),
    object: zSparqlValue,
    graph: z.object({
        type: z.enum(['default', 'uri']),
        value: z.string()
    })
});

export const zSparqlQuadsResults = z.object({
    head: z.object({
        link: z.array(z.string()).nullish()
    }),
    results: z.object({
        quads: z.array(zSparqlQuad)
    })
});

export const zSparqlSelectResults = z.object({
    head: z.object({
        vars: z.array(z.string()),
        link: z.array(z.string()).nullish()
    }),
    results: z.object({
        bindings: z.array(zSparqlBinding)
    })
});

export const zSparqlQueryResponse = z.union([
    zSparqlSelectResults,
    zSparqlAskResults,
    zSparqlQuadsResults
]).nullable();

/**
 * Transaction behavior for source access.
 */
export const zTransactionMode = z.enum([
    'write',
    'read',
    'deferred'
]);

export const zSource = z.union([
    z.string(),
    z.object({
        name: z.string().optional(),
        id: z.string().optional(),
        namespace: z.string().optional(),
        mode: zTransactionMode.optional()
    })
]);

export const zDeleteWorldRequest = z.object({
    source: zSource
});

export const zExportWorldRequest = z.object({
    source: zSource,
    contentType: zContentType.optional()
});

export const zGetWorldRequest = z.object({
    source: zSource
});

export const zImportWorldRequest = z.object({
    source: zSource,
    data: z.string(),
    contentType: zContentType.optional()
});

export const zSearchWorldsRequest = z.object({
    sources: z.array(zSource).optional(),
    parent: z.string().optional(),
    query: z.string(),
    pageSize: z.int().optional(),
    pageToken: z.string().optional(),
    subjects: z.array(z.string()).optional(),
    predicates: z.array(z.string()).optional(),
    types: z.array(z.string()).optional()
});

export const zSparqlQueryRequest = z.object({
    sources: z.array(zSource).optional(),
    parent: z.string().optional(),
    query: z.string(),
    defaultGraphUris: z.array(z.string()).optional(),
    namedGraphUris: z.array(z.string()).optional()
});

export const zUpdateWorldRequest = z.object({
    source: zSource,
    displayName: z.string().optional(),
    description: z.string().optional()
});

/**
 * A branded identifier for a World resource.
 */
export const zWorldId = z.string();

/**
 * Metadata for a single world.
 */
export const zWorld = z.object({
    name: z.string().readonly().optional(),
    id: zWorldId.optional(),
    namespace: z.string().optional(),
    displayName: z.string(),
    description: z.string().optional(),
    createTime: z.number().optional(),
    updateTime: z.number().optional(),
    deleteTime: z.number().nullish()
});

export const zListWorldsResponse = z.object({
    worlds: z.array(zWorld),
    nextPageToken: z.string().optional()
});

export const zSearchResult = z.object({
    subject: z.string(),
    predicate: z.string(),
    object: z.string(),
    vecRank: z.number().nullish(),
    ftsRank: z.number().nullish(),
    score: z.number(),
    world: zWorld
});

/**
 * Metadata for a single world.
 */
export const zWorldWritable = z.object({
    id: zWorldId.optional(),
    namespace: z.string().optional(),
    displayName: z.string(),
    description: z.string().optional(),
    createTime: z.number().optional(),
    updateTime: z.number().optional(),
    deleteTime: z.number().nullish()
});

export const zListWorldsResponseWritable = z.object({
    worlds: z.array(zWorldWritable),
    nextPageToken: z.string().optional()
});

export const zSearchResultWritable = z.object({
    subject: z.string(),
    predicate: z.string(),
    object: z.string(),
    vecRank: z.number().nullish(),
    ftsRank: z.number().nullish(),
    score: z.number(),
    world: zWorldWritable
});

export const zWorldsRpcBody = z.union([
    zGetWorldRequest,
    zCreateWorldRequest,
    zUpdateWorldRequest,
    zDeleteWorldRequest,
    zListWorldsRequest,
    zImportWorldRequest,
    zExportWorldRequest,
    zSearchWorldsRequest,
    zSparqlQueryRequest
]);

/**
 * Success
 */
export const zWorldsRpcResponse = z.union([
    zWorld,
    zListWorldsResponse,
    zSparqlQueryResponse,
    z.object({
        results: z.array(zSearchResult).optional(),
        nextPageToken: z.string().optional()
    })
]);
