// This file was generated by sql-embedder. Do not edit manually.

/**
 * accountsTable
 * An account owns 0 or more worlds
 * TODO: Rename "accounts" to "tenants" to better reflect that it represents an organization/environment rather than a user
 */
export const accountsTable =
  "CREATE TABLE IF NOT EXISTS accounts (\r\n    id TEXT PRIMARY KEY NOT NULL,\r\n    description TEXT,\r\n    plan TEXT,\r\n    api_key TEXT NOT NULL,\r\n    created_at INTEGER NOT NULL,\r\n    updated_at INTEGER NOT NULL,\r\n    deleted_at INTEGER\r\n)";

/**
 * accountsApiKeyIndex
 * Index on api_key for secondary lookups (was a kvdex secondary index)
 */
export const accountsApiKeyIndex =
  "CREATE INDEX IF NOT EXISTS idx_accounts_api_key ON accounts(api_key)";

/**
 * accountsGetMany
 * Get accounts with pagination (used in GET /v1/accounts)
 */
export const accountsGetMany =
  "SELECT * FROM accounts\r\nWHERE deleted_at IS NULL\r\nORDER BY created_at DESC\r\nLIMIT ? OFFSET ?";

/**
 * accountsAdd
 * Insert a new account (used in POST /v1/accounts)
 */
export const accountsAdd =
  "INSERT INTO accounts (id, description, plan, api_key, created_at, updated_at, deleted_at)\r\nVALUES (?, ?, ?, ?, ?, ?, ?)";

/**
 * accountsFind
 * Find account by ID (used in GET /v1/accounts/:account and auth middleware)
 */
export const accountsFind =
  "SELECT * FROM accounts\r\nWHERE id = ? AND deleted_at IS NULL";

/**
 * accountsFindByApiKey
 * Find account by API key (used in auth middleware)
 */
export const accountsFindByApiKey =
  "SELECT * FROM accounts\r\nWHERE api_key = ? AND deleted_at IS NULL";

/**
 * accountsUpdate
 * Update account fields (used in PUT /v1/accounts/:account)
 */
export const accountsUpdate =
  "UPDATE accounts\r\nSET description = ?, plan = ?, updated_at = ?\r\nWHERE id = ?";

/**
 * accountsRotateApiKey
 * Rotate account API key (used in POST /v1/accounts/:account/rotate)
 */
export const accountsRotateApiKey =
  "UPDATE accounts\r\nSET api_key = ?, updated_at = ?\r\nWHERE id = ?";

/**
 * accountsDelete
 * Delete account (used in DELETE /v1/accounts/:account)
 */
export const accountsDelete = "DELETE FROM accounts\r\nWHERE id = ?";
