// This file was generated by sql-embedder. Do not edit manually.

/**
 * invitesTable is a table where each invite allows a user to be promoted to the free plan.
 * An invite allows a user with a nullish plan to be promoted to the free plan
 * upon redemption. Once redeemed, the invite cannot be used again.
 */
export const invitesTable =
  "CREATE TABLE IF NOT EXISTS invites (\r\n    code TEXT PRIMARY KEY NOT NULL,\r\n    created_at INTEGER NOT NULL,\r\n    redeemed_by TEXT,\r\n    redeemed_at INTEGER\r\n);";

/**
 * invitesRedeemedByIndex
 * Index on redeemed_by for secondary lookups (was a kvdex secondary index)
 */
export const invitesRedeemedByIndex =
  "CREATE INDEX IF NOT EXISTS idx_invites_redeemed_by ON invites(redeemed_by);";

/**
 * invitesGetMany
 * Get invites with pagination (used in GET /v1/invites)
 */
export const invitesGetMany =
  "SELECT * FROM invites\r\nORDER BY created_at DESC\r\nLIMIT ? OFFSET ?;";

/**
 * invitesAdd
 * Insert a new invite (used in POST /v1/invites)
 */
export const invitesAdd =
  "INSERT INTO invites (code, created_at, redeemed_by, redeemed_at)\r\nVALUES (?, ?, ?, ?);";

/**
 * invitesFind
 * Find invite by code (used in GET /v1/invites/:code and POST /v1/invites/:code/redeem)
 */
export const invitesFind = "SELECT * FROM invites\r\nWHERE code = ?;";

/**
 * invitesUpdate
 * Update invite (mark as redeemed in POST /v1/invites/:code/redeem)
 */
export const invitesUpdate =
  "UPDATE invites\r\nSET redeemed_by = ?, redeemed_at = ?\r\nWHERE code = ?;";

/**
 * invitesDelete
 * Delete invite (used in DELETE /v1/invites/:code)
 */
export const invitesDelete = "DELETE FROM invites\r\nWHERE code = ?;";
