// This file was generated by sql-embedder. Do not edit manually.

/**
 * tenantsTable is a table where each tenant owns zero or more worlds.
 */
export const tenantsTable =
  "CREATE TABLE IF NOT EXISTS tenants (\r\n    id TEXT PRIMARY KEY NOT NULL,\r\n    description TEXT,\r\n    plan TEXT,\r\n    api_key TEXT NOT NULL,\r\n    created_at INTEGER NOT NULL,\r\n    updated_at INTEGER NOT NULL,\r\n    deleted_at INTEGER\r\n);";

/**
 * tenantsApiKeyIndex
 * Index on api_key for secondary lookups
 */
export const tenantsApiKeyIndex =
  "CREATE INDEX IF NOT EXISTS idx_tenants_api_key ON tenants(api_key);";

/**
 * tenantsGetMany
 * Get tenants with pagination (used in GET /v1/tenants)
 */
export const tenantsGetMany =
  "SELECT * FROM tenants\r\nWHERE deleted_at IS NULL\r\nORDER BY created_at DESC\r\nLIMIT ? OFFSET ?;";

/**
 * tenantsAdd
 * Insert a new tenant (used in POST /v1/tenants)
 */
export const tenantsAdd =
  "INSERT INTO tenants (id, description, plan, api_key, created_at, updated_at, deleted_at)\r\nVALUES (?, ?, ?, ?, ?, ?, ?);";

/**
 * tenantsFind
 * Find tenant by ID (used in GET /v1/tenants/:tenant and auth middleware)
 */
export const tenantsFind =
  "SELECT * FROM tenants\r\nWHERE id = ? AND deleted_at IS NULL;";

/**
 * tenantsFindByApiKey
 * Find tenant by API key (used in auth middleware)
 */
export const tenantsFindByApiKey =
  "SELECT * FROM tenants\r\nWHERE api_key = ? AND deleted_at IS NULL;";

/**
 * tenantsUpdate
 * Update tenant fields (used in PUT /v1/tenants/:tenant)
 */
export const tenantsUpdate =
  "UPDATE tenants\r\nSET description = ?, plan = ?, updated_at = ?\r\nWHERE id = ?;";

/**
 * tenantsRotateApiKey
 * Rotate tenant API key (used in POST /v1/tenants/:tenant/rotate)
 */
export const tenantsRotateApiKey =
  "UPDATE tenants\r\nSET api_key = ?, updated_at = ?\r\nWHERE id = ?;";

/**
 * tenantsDelete
 * Delete tenant (used in DELETE /v1/tenants/:tenant)
 */
export const tenantsDelete = "DELETE FROM tenants\r\nWHERE id = ?;";
