// This file was generated by sql-embedder. Do not edit manually.

/**
 * worldsTable
 * A world is owned by an account
 * TODO: Make account_id nullable to support admin-created (non-account scoped) worlds
 */
export const worldsTable =
  "CREATE TABLE IF NOT EXISTS worlds (\r\n    id TEXT PRIMARY KEY NOT NULL,\r\n    account_id TEXT NOT NULL,\r\n    label TEXT NOT NULL,\r\n    description TEXT,\r\n    blob BLOB,\r\n    created_at INTEGER NOT NULL,\r\n    updated_at INTEGER NOT NULL,\r\n    deleted_at INTEGER,\r\n    is_public INTEGER DEFAULT 0, -- SQLite uses INTEGER for boolean: 0 = false, 1 = true\r\n    FOREIGN KEY (account_id) REFERENCES accounts(id)\r\n)";

/**
 * worldsAccountIdIndex
 * Index on account_id for secondary lookups (was a kvdex secondary index)
 */
export const worldsAccountIdIndex =
  "CREATE INDEX IF NOT EXISTS idx_worlds_account_id ON worlds(account_id)";

/**
 * worldsFind
 * Find world by ID (metadata only)
 */
export const worldsFind =
  "SELECT id, account_id, label, description, created_at, updated_at, deleted_at, is_public FROM worlds\r\nWHERE id = ? AND deleted_at IS NULL";

/**
 * worldsGetBlob
 * Get only the RDF blob for a world
 */
export const worldsGetBlob =
  "SELECT blob FROM worlds\r\nWHERE id = ? AND deleted_at IS NULL";

/**
 * worldsFindByAccountId
 * Find worlds by account ID with pagination (metadata only)
 */
export const worldsFindByAccountId =
  "SELECT id, account_id, label, description, created_at, updated_at, deleted_at, is_public FROM worlds\r\nWHERE account_id = ? AND deleted_at IS NULL\r\nORDER BY created_at DESC\r\nLIMIT ? OFFSET ?";

/**
 * worldsAdd
 * Insert a new world (metadata and initial blob)
 */
export const worldsAdd =
  "INSERT INTO worlds (id, account_id, label, description, blob, created_at, updated_at, deleted_at, is_public)\r\nVALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";

/**
 * worldsUpdate
 * Update world fields (used in PUT /v1/worlds/:world)
 */
export const worldsUpdate =
  "UPDATE worlds\r\nSET label = ?, description = ?, is_public = ?, updated_at = ?\r\nWHERE id = ?";

/**
 * worldsSetBlob
 * Update the world's RDF blob (used in SPARQL update operations)
 */
export const worldsSetBlob =
  "UPDATE worlds\r\nSET blob = ?, updated_at = ?\r\nWHERE id = ?";

/**
 * worldsDelete
 * Delete world (used in DELETE /v1/worlds/:world)
 */
export const worldsDelete = "DELETE FROM worlds\r\nWHERE id = ?";
