// This file was generated by sql-embedder. Do not edit manually.

/**
 * worldsTable is a table where each world is owned by a tenant.
 * TODO: Make tenant_id nullable to support admin-created (non-tenant scoped) worlds
 */
export const worldsTable =
  "CREATE TABLE IF NOT EXISTS worlds (\r\n    id TEXT PRIMARY KEY NOT NULL,\r\n    tenant_id TEXT NOT NULL,\r\n    label TEXT NOT NULL,\r\n    description TEXT,\r\n    blob BLOB,\r\n    created_at INTEGER NOT NULL,\r\n    updated_at INTEGER NOT NULL,\r\n    deleted_at INTEGER,\r\n    is_public INTEGER DEFAULT 0, -- SQLite uses INTEGER for boolean: 0 = false, 1 = true\r\n    FOREIGN KEY (tenant_id) REFERENCES tenants(id)\r\n);";

/**
 * worldsTenantIdIndex
 * Index on tenant_id for secondary lookups
 */
export const worldsTenantIdIndex =
  "CREATE INDEX IF NOT EXISTS idx_worlds_tenant_id ON worlds(tenant_id);";

/**
 * worldsFind
 * Find world by ID (used in GET /v1/worlds/:world and SPARQL routes)
 */
export const worldsFind =
  "SELECT * FROM worlds\r\nWHERE id = ? AND deleted_at IS NULL;";

/**
 * worldsFindByTenantId
 * Find worlds by tenant ID with pagination (used in GET /v1/worlds)
 */
export const worldsFindByTenantId =
  "SELECT * FROM worlds\r\nWHERE tenant_id = ? AND deleted_at IS NULL\r\nORDER BY created_at DESC\r\nLIMIT ? OFFSET ?;";

/**
 * worldsAdd
 * Insert a new world (used in POST /v1/worlds)
 */
export const worldsAdd =
  "INSERT INTO worlds (id, tenant_id, label, description, blob, created_at, updated_at, deleted_at, is_public)\r\nVALUES (?, ?, ?, ?, ?, ?, ?, ?, ?);";

/**
 * worldsUpdate
 * Update world fields (used in PUT /v1/worlds/:world)
 */
export const worldsUpdate =
  "UPDATE worlds\r\nSET label = ?, description = ?, is_public = ?, updated_at = ?, blob = ?\r\nWHERE id = ?;";

/**
 * worldsDelete
 * Delete world (used in DELETE /v1/worlds/:world)
 */
export const worldsDelete = "DELETE FROM worlds\r\nWHERE id = ?;";
