// This file was generated by sql-embedder. Do not edit manually.

/**
 * itemTypesTable is a table for mapping entities to their types.
 */
export const itemTypesTable =
  "CREATE TABLE IF NOT EXISTS item_types (\r\n  subject TEXT NOT NULL,\r\n  type TEXT NOT NULL,\r\n  PRIMARY KEY (subject, type)\r\n) WITHOUT ROWID;";

/**
 * itemTypesIndex is a composite index for efficient type-based filtering.
 */
export const itemTypesIndex =
  "CREATE INDEX IF NOT EXISTS idx_item_type_mapping ON item_types (type, subject);";

/**
 * triplesItemTypeInsertTrigger is a trigger to sync item_types after inserting an rdf:type triple.
 */
export const triplesItemTypeInsertTrigger =
  "CREATE TRIGGER IF NOT EXISTS triples_type_ai\r\nAFTER INSERT ON triples\r\nWHEN new.predicate = 'http://www.w3.org/1999/02/22-rdf-syntax-ns#type'\r\nBEGIN\r\n  INSERT OR REPLACE INTO item_types (subject, type) VALUES (new.subject, new.object);\r\nEND;";

/**
 * triplesItemTypeDeleteTrigger is a trigger to sync item_types after deleting an rdf:type triple.
 */
export const triplesItemTypeDeleteTrigger =
  "CREATE TRIGGER IF NOT EXISTS triples_type_ad\r\nAFTER DELETE ON triples\r\nWHEN old.predicate = 'http://www.w3.org/1999/02/22-rdf-syntax-ns#type'\r\nBEGIN\r\n  DELETE FROM item_types WHERE subject = old.subject AND type = old.object;\r\nEND;";
