// This file was generated by sql-embedder. Do not edit manually.

/**
 * entityTypesTable is a table for mapping entities to their types.
 */
export const entityTypesTable =
  "CREATE TABLE IF NOT EXISTS entity_types (\r\n  subject TEXT NOT NULL,\r\n  type TEXT NOT NULL,\r\n  PRIMARY KEY (subject, type)\r\n) WITHOUT ROWID;";

/**
 * entityTypesIndex is a composite index for efficient type-based filtering.
 */
export const entityTypesIndex =
  "CREATE INDEX IF NOT EXISTS idx_entity_type_mapping ON entity_types (type, subject);";

/**
 * triplesTypeInsertTrigger is a trigger to sync entity_types after inserting an rdf:type triple.
 */
export const triplesTypeInsertTrigger =
  "CREATE TRIGGER IF NOT EXISTS triples_type_ai\r\nAFTER INSERT ON triples\r\nWHEN new.predicate = 'http://www.w3.org/1999/02/22-rdf-syntax-ns#type'\r\nBEGIN\r\n  INSERT OR REPLACE INTO entity_types (subject, type) VALUES (new.subject, new.object);\r\nEND;";

/**
 * triplesTypeDeleteTrigger is a trigger to sync entity_types after deleting an rdf:type triple.
 */
export const triplesTypeDeleteTrigger =
  "CREATE TRIGGER IF NOT EXISTS triples_type_ad\r\nAFTER DELETE ON triples\r\nWHEN old.predicate = 'http://www.w3.org/1999/02/22-rdf-syntax-ns#type'\r\nBEGIN\r\n  DELETE FROM entity_types WHERE subject = old.subject AND type = old.object;\r\nEND;";
