// This file is auto-generated by @hey-api/openapi-ts

import { client } from './client.gen.ts';
import type { Client, Options as Options2, TDataShape } from './client/index.ts';
import type { WorldsRpcData, WorldsRpcResponses } from './types.gen.ts';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Unified RPC endpoint for worlds.
 */
export const worldsRpc = <ThrowOnError extends boolean = false>(options: Options<WorldsRpcData, ThrowOnError>) => (options.client ?? client).post<WorldsRpcResponses, unknown, ThrowOnError>({
    url: '/rpc/worlds',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
