/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/rpc/worlds": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Unified RPC endpoint for worlds. */
    post: operations["worldsRpc"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * @description Supported RDF serialization content types.
     * @enum {string}
     */
    ContentType:
      | "text/turtle"
      | "application/n-quads"
      | "application/n-triples"
      | "text/n3";
    /**
     * @description Transaction behavior for source access.
     * @enum {string}
     */
    TransactionMode: "write" | "read" | "deferred";
    ErrorResponseData: {
      error: {
        message: string;
      };
    };
    Log: {
      level: string;
      message: string;
      /** Format: int64 */
      timestamp: number;
      metadata?: {
        [key: string]: unknown;
      };
    };
    /** @description A branded identifier for a World resource. */
    WorldId: string;
    /** @description A branded identifier for a Fact resource. */
    FactId: string;
    /** @description A branded identifier for a Chunk resource. */
    ChunkId: string;
    /** @description Metadata for a single world. */
    World: {
      /** @description The canonical resource name. */
      readonly name?: string;
      id?: components["schemas"]["WorldId"];
      namespace?: string;
      displayName: string;
      description?: string;
      /** Format: int64 */
      createTime?: number;
      /** Format: int64 */
      updateTime?: number;
      /** Format: int64 */
      deleteTime?: number | null;
    };
    /** @description A single triple/quad in a world. */
    Fact: {
      id?: components["schemas"]["FactId"];
      subject: string;
      predicate: string;
      object: string;
      type: string;
      lang?: string;
      datatype?: string;
      world_id?: string;
      /** Format: int64 */
      created_at?: number;
      /** Format: int64 */
      deleted_at?: number | null;
    };
    /** @description A text chunk with an optional embedding vector. */
    Chunk: {
      id: components["schemas"]["ChunkId"];
      fact_id: string;
      subject: string;
      predicate: string;
      text: string;
      /**
       * Format: byte
       * @description Base64-encoded embedding vector (Uint8Array).
       */
      vector?: string | null;
    };
    Source: string | {
      name?: string;
      id?: string;
      namespace?: string;
      mode?: components["schemas"]["TransactionMode"];
    };
    /** @description A value in a SPARQL result. */
    SparqlValue: {
      /** @enum {string} */
      type: "uri";
      value: string;
    } | {
      /** @enum {string} */
      type: "bnode";
      value: string;
    } | {
      /** @enum {string} */
      type: "literal";
      value: string;
      "xml:lang"?: string;
      datatype?: string;
    } | {
      /** @enum {string} */
      type: "triple";
      value: {
        subject: components["schemas"]["SparqlValue"];
        predicate: components["schemas"]["SparqlValue"];
        object: components["schemas"]["SparqlValue"];
      };
    };
    SparqlBinding: {
      [key: string]: components["schemas"]["SparqlValue"];
    };
    SparqlSelectResults: {
      head: {
        vars: string[];
        link?: string[] | null;
      };
      results: {
        bindings: components["schemas"]["SparqlBinding"][];
      };
    };
    SparqlAskResults: {
      head: {
        link?: string[] | null;
      };
      boolean: boolean;
    };
    SparqlQuad: {
      subject: {
        /** @enum {string} */
        type: "uri" | "bnode";
        value: string;
      };
      predicate: {
        /** @enum {string} */
        type: "uri";
        value: string;
      };
      object: components["schemas"]["SparqlValue"];
      graph: {
        /** @enum {string} */
        type: "default" | "uri";
        value: string;
      };
    };
    SparqlQuadsResults: {
      head: {
        link?: string[] | null;
      };
      results: {
        quads: components["schemas"]["SparqlQuad"][];
      };
    };
    SparqlQueryResponse:
      | components["schemas"]["SparqlSelectResults"]
      | components["schemas"]["SparqlAskResults"]
      | components["schemas"]["SparqlQuadsResults"]
      | null;
    SearchResult: {
      subject: string;
      predicate: string;
      object: string;
      vecRank?: number | null;
      ftsRank?: number | null;
      score: number;
      world: components["schemas"]["World"];
    };
    GetWorldRequest: {
      source: components["schemas"]["Source"];
    };
    CreateWorldRequest: {
      parent?: string;
      id?: string;
      displayName?: string;
      description?: string;
    };
    UpdateWorldRequest: {
      source: components["schemas"]["Source"];
      displayName?: string;
      description?: string;
    };
    DeleteWorldRequest: {
      source: components["schemas"]["Source"];
    };
    ListWorldsRequest: {
      parent?: string;
      pageSize?: number;
      pageToken?: string;
    };
    ListWorldsResponse: {
      worlds: components["schemas"]["World"][];
      nextPageToken?: string;
    };
    ImportWorldRequest: {
      source: components["schemas"]["Source"];
      data: string;
      contentType?: components["schemas"]["ContentType"];
    };
    ExportWorldRequest: {
      source: components["schemas"]["Source"];
      contentType?: components["schemas"]["ContentType"];
    };
    SearchWorldsRequest: {
      sources?: components["schemas"]["Source"][];
      parent?: string;
      query: string;
      pageSize?: number;
      pageToken?: string;
      subjects?: string[];
      predicates?: string[];
      types?: string[];
    };
    SparqlQueryRequest: {
      sources?: components["schemas"]["Source"][];
      parent?: string;
      query: string;
      defaultGraphUris?: string[];
      namedGraphUris?: string[];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  worldsRpc: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json":
          | components["schemas"]["GetWorldRequest"]
          | components["schemas"]["CreateWorldRequest"]
          | components["schemas"]["UpdateWorldRequest"]
          | components["schemas"]["DeleteWorldRequest"]
          | components["schemas"]["ListWorldsRequest"]
          | components["schemas"]["ImportWorldRequest"]
          | components["schemas"]["ExportWorldRequest"]
          | components["schemas"]["SearchWorldsRequest"]
          | components["schemas"]["SparqlQueryRequest"];
      };
    };
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json":
            | components["schemas"]["World"]
            | components["schemas"]["ListWorldsResponse"]
            | components["schemas"]["SparqlQueryResponse"]
            | {
              results?: components["schemas"]["SearchResult"][];
              nextPageToken?: string;
            };
        };
      };
    };
  };
}
