// This file was generated by sql-embedder. Do not edit manually.

/**
 * worldsTable initializes the worlds table.
 */
export const worldsTable =
  "CREATE TABLE IF NOT EXISTS worlds (\r\n  id TEXT PRIMARY KEY NOT NULL,\r\n  namespace_id TEXT NOT NULL,\r\n  slug TEXT NOT NULL,\r\n  label TEXT NOT NULL,\r\n  description TEXT,\r\n  db_hostname TEXT,\r\n  db_token TEXT,\r\n  created_at INTEGER NOT NULL,\r\n  updated_at INTEGER NOT NULL,\r\n  deleted_at INTEGER,\r\n  UNIQUE(slug, namespace_id)\r\n);";

/**
 * selectWorldById is a query that finds a world by ID
 */
export const selectWorldById =
  "SELECT\r\n  id,\r\n  namespace_id,\r\n  slug,\r\n  label,\r\n  description,\r\n  db_hostname,\r\n  db_token,\r\n  created_at,\r\n  updated_at,\r\n  deleted_at\r\nFROM\r\n  worlds\r\nWHERE\r\n  id = ?\r\n  AND namespace_id = ?\r\n  AND deleted_at IS NULL;";

/**
 * selectWorldByIdInternal is a query that finds a world by ID without namespace scoping.
 * Use this ONLY for internal system operations where the ID has already been validated.
 */
export const selectWorldByIdInternal =
  "SELECT\r\n  id,\r\n  namespace_id,\r\n  slug,\r\n  label,\r\n  description,\r\n  db_hostname,\r\n  db_token,\r\n  created_at,\r\n  updated_at,\r\n  deleted_at\r\nFROM\r\n  worlds\r\nWHERE\r\n  id = ?\r\n  AND deleted_at IS NULL;";

/**
 * selectWorldBySlug is a query that finds a world by slug.
 */
export const selectWorldBySlug =
  "SELECT\r\n  id,\r\n  namespace_id,\r\n  slug,\r\n  label,\r\n  description,\r\n  db_hostname,\r\n  db_token,\r\n  created_at,\r\n  updated_at,\r\n  deleted_at\r\nFROM\r\n  worlds\r\nWHERE\r\n  slug = ?\r\n  AND namespace_id = ?\r\n  AND deleted_at IS NULL;";

/**
 * selectAllWorlds is a query that finds worlds for a specific namespace.
 */
export const selectAllWorlds =
  "SELECT\r\n  id,\r\n  namespace_id,\r\n  slug,\r\n  label,\r\n  description,\r\n  db_hostname,\r\n  db_token,\r\n  created_at,\r\n  updated_at,\r\n  deleted_at\r\nFROM\r\n  worlds\r\nWHERE\r\n  namespace_id = ?\r\n  AND deleted_at IS NULL\r\nORDER BY\r\n  created_at DESC\r\nLIMIT\r\n  ? OFFSET ?;";

/**
 * insertWorld is a query that inserts a new world (used in POST /worlds).
 */
export const insertWorld =
  "INSERT INTO\r\n  worlds (\r\n    id,\r\n    namespace_id,\r\n    slug,\r\n    label,\r\n    description,\r\n    db_hostname,\r\n    db_token,\r\n    created_at,\r\n    updated_at,\r\n    deleted_at\r\n  )\r\nVALUES\r\n  (?, ?, ?, ?, ?, ?, ?, ?, ?, ?);";

/**
 * updateWorld is a query that updates world fields
 * (used in PUT /worlds/:world).
 */
export const updateWorld =
  "UPDATE\r\n  worlds\r\nSET\r\n  slug = ?,\r\n  label = ?,\r\n  description = ?,\r\n  updated_at = ?,\r\n  db_hostname = ?,\r\n  db_token = ?,\r\n  deleted_at = ?\r\nWHERE\r\n  id = ?\r\n  AND namespace_id = ?;";

/**
 * deleteWorld is a query that deletes a world
 * (used in DELETE /worlds/:world).
 */
export const deleteWorld =
  "DELETE FROM\r\n  worlds\r\nWHERE\r\n  id = ?\r\n  AND namespace_id = ?;";
