// This file was generated by sql-embedder. Do not edit manually.

/**
 * worldsTable initializes the worlds table.
 */
export const worldsTable =
  "CREATE TABLE IF NOT EXISTS worlds (\n  namespace_id TEXT NOT NULL,\n  slug TEXT NOT NULL,\n  label TEXT NOT NULL,\n  description TEXT,\n  db_hostname TEXT,\n  db_token TEXT,\n  created_at INTEGER NOT NULL,\n  updated_at INTEGER NOT NULL,\n  deleted_at INTEGER,\n  PRIMARY KEY (namespace_id, slug)\n);";

/**
 * selectWorldBySlug is a query that finds a world by slug.
 */
export const selectWorldBySlug =
  "SELECT\n  namespace_id,\n  slug,\n  label,\n  description,\n  db_hostname,\n  db_token,\n  created_at,\n  updated_at,\n  deleted_at\nFROM\n  worlds\nWHERE\n  slug = ?\n  AND namespace_id = ?\n  AND deleted_at IS NULL;";

/**
 * selectWorldBySlugInternal is a query that finds a world by slug without namespace scoping.
 * Use this ONLY for internal system operations where the slug has already been validated.
 */
export const selectWorldBySlugInternal =
  "SELECT\n  namespace_id,\n  slug,\n  label,\n  description,\n  db_hostname,\n  db_token,\n  created_at,\n  updated_at,\n  deleted_at\nFROM\n  worlds\nWHERE\n  slug = ?\n  AND deleted_at IS NULL;";

/**
 * selectAllWorlds is a query that finds worlds for a specific namespace.
 */
export const selectAllWorlds =
  "SELECT\n  namespace_id,\n  slug,\n  label,\n  description,\n  db_hostname,\n  db_token,\n  created_at,\n  updated_at,\n  deleted_at\nFROM\n  worlds\nWHERE\n  namespace_id = ?\n  AND deleted_at IS NULL\nORDER BY\n  created_at DESC\nLIMIT\n  ? OFFSET ?;";

/**
 * insertWorld is a query that inserts a new world (used in POST /worlds).
 */
export const insertWorld =
  "INSERT INTO\n  worlds (\n    namespace_id,\n    slug,\n    label,\n    description,\n    db_hostname,\n    db_token,\n    created_at,\n    updated_at,\n    deleted_at\n  )\nVALUES\n  (?, ?, ?, ?, ?, ?, ?, ?, ?);";

/**
 * updateWorld is a query that updates world fields
 * (used in PUT /worlds/:world).
 */
export const updateWorld =
  "UPDATE\n  worlds\nSET\n  label = ?,\n  description = ?,\n  updated_at = ?,\n  db_hostname = ?,\n  db_token = ?,\n  deleted_at = ?\nWHERE\n  slug = ?\n  AND namespace_id = ?;";

/**
 * deleteWorld is a query that deletes a world
 * (used in DELETE /worlds/:world).
 */
export const deleteWorld =
  "DELETE FROM\n  worlds\nWHERE\n  slug = ?\n  AND namespace_id = ?;";
