name: Check
"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  check:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v5
      - uses: denoland/setup-deno@v2
      - name: Format
        run: deno fmt --check
      - name: Lint
        run: deno lint
      - name: Environment Info
        run: deno --version && deno info
      - name: Test
        run: deno cache --reload packages/worlds/src/mod.ts && deno task test --trace-leaks
